### ISSUE TITLE
Cache Cargo dependencies in a separate layer

### ISSUE THREAD

**Issue by OldFrostDragon** [maxymkuz/mini_google#5]
Hi @maxymkuz and @LastGenius-edu,

Please take a look at the next Dockerfile snippet.

```dockerfile
FROM ekidd/rust-musl-builder:latest AS builder

RUN mkdir -p /home/rust/my-project
WORKDIR /home/rust/my-project
VOLUME ["/home/rust/myproject"]

# cache dependency artifacts. 'Cargo build' builds 
# both dependencies and project files, 
# splitting the project into dependencies with single 
# empty main and current project sources.
COPY --chown=rust:rust Cargo.toml Cargo.toml
COPY --chown=rust:rust Cargo.lock Cargo.lock
RUN echo 'fn main() {}' > src/main.rs
RUN cargo build --release

# build the project using prebuilt deps
RUN rm /home/rust/my-project/src/main.rs
COPY --chown=rust:rust ./src ./src
RUN cargo build --release
```

This trick solves the issue with dependencies caching during `cargo build`. It splits the build process into two steps: first builds dependencies with an empty `main` and commits the separate image layer. Docker will reuse this layer later during the project build.  .`

This is just a prototype that needs to be implemented for each Rust project. There is no need to use a separate project; you can implement it for `/home/rust/src`.

**Comment by LastGenius-edu** [comment]
Thanks :) 

Started implementing this in 954540d
